# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2675c700aced91c10909f5a9fc23befcde8e2ec0dea41f24e41aef410a59455f6af12e7917aa37f30085de44e28f9eb7ed8de3847261bef19609757a5c17084

test:
  secret_key_base: 0ca968f019df702a8fee2bcedb9f05f37bdb3ddc17d2e2425410038899d16259dad2bfd59ec1726d8240dd65f1deef5633a2c74af623d22c51baf1571e675b1a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
